#!/bin/zsh
# AutoForkClone.sh
# Automates GitHub fork → clone → setup (with optional feature branch)
# Repos are cloned into $HOME/Documents/GitHub

# Source function library with error handling
FORMAT_LIBRARY="$HOME/ShellScripts/FLibFormatPrintf.sh"
[[ -f "$FORMAT_LIBRARY" ]] || { printf "Error: Required library $FORMAT_LIBRARY not found" >&2; exit 1; }
source "$FORMAT_LIBRARY"

# --- CONFIG ---
BASE_DIR="$HOME/Documents/GitHub"

# --- FUNCTIONS ---
usage() {
  cat << EOF
Usage: $0 [<github-repo-url>] [feature-branch-name]

If no URL is provided, you'll be prompted to enter one.

Examples:
  $0 https://github.com/someuser/project
  $0 https://github.com/someuser/project feature/update-readme
  $0  # Interactive mode - prompts for URL

EOF
  exit 1
}

validate_url() {
  local url="$1"
  if [[ ! "$url" =~ ^https://github\.com/[^/]+/[^/]+/?$ ]]; then
    error_printf "Invalid GitHub URL format. Expected: https://github.com/username/repo"
    return 1
  fi
  return 0
}

check_gh_auth() {
  if ! gh auth status &>/dev/null; then
    error_printf "Not authenticated with GitHub CLI. Please run: gh auth login" true
  fi
}

create_setup_summary() {
  local summary_file="$LOCAL_PATH/SETUP_SUMMARY.md"
  local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
  
  cat > "$summary_file" << EOF
# Setup Summary

**Generated:** $timestamp

## Repository Information

- **Local Path:** \`$LOCAL_PATH\`
- **Fork URL:** $FORK_URL
- **Upstream URL:** $REPO_URL
- **Repository Name:** $REPO_NAME
- **GitHub User:** $GITHUB_USER
$(if [[ -n "$FEATURE_BRANCH" ]]; then echo "- **Feature Branch:** \`$FEATURE_BRANCH\`"; fi)

## Git Remotes

\`\`\`
$(git remote -v)
\`\`\`

## Next Steps

### 1. Navigate to repository
\`\`\`bash
cd "$LOCAL_PATH"
\`\`\`

### 2. Make your changes

### 3. Commit and push
\`\`\`bash
git add .
git commit -m "Your descriptive commit message"
git push origin ${FEATURE_BRANCH:-main}
\`\`\`

### 4. Create a pull request
\`\`\`bash
gh pr create --web
\`\`\`

---
*This file was automatically generated by AutoForkClone.sh*
EOF

  success_printf "Setup summary saved to: $summary_file"
}

# --- MAIN ---
clear
format_printf "Auto Fork and Clone..." "yellow" "bold"
printf "\n"
[[ "$1" == "-h" || "$1" == "--help" ]] && usage

# Check GitHub CLI authentication first
check_gh_auth

# Get GitHub username
GITHUB_USER=$(gh api user --jq .login 2>/dev/null)
if [[ -z "$GITHUB_USER" ]]; then
  error_printf "Failed to get GitHub username. Check your authentication." true
fi

# Get repo URL (from argument or prompt)
if [[ -z "$1" ]]; then
  read -r "REPO_URL?Enter the GitHub repository URL to fork: "
  REPO_URL="${REPO_URL## }"  # Trim leading whitespace
  REPO_URL="${REPO_URL%% }"  # Trim trailing whitespace
  [[ -z "$REPO_URL" ]] && { error_printf "No URL provided" true; }
else
  REPO_URL="$1"
fi

# Remove trailing slash if present
REPO_URL="${REPO_URL%/}"

# Validate URL
validate_url "$REPO_URL" || exit 1

# Parse repo information
REPO_NAME=$(basename "$REPO_URL" .git)
ORIGINAL_USER=$(echo "$REPO_URL" | sed -E 's#https://github\.com/([^/]+)/.*#\1#')

# Check if forking your own repo
if [[ "$ORIGINAL_USER" == "$GITHUB_USER" ]]; then
  read -r "response?⚠️  This is already your repository. Do you want to just clone it? (y/n) "
  if [[ "$response" =~ ^[Yy]$ ]]; then
    FORK_URL="$REPO_URL"
    SKIP_FORK=true
  else
    info_printf "Operation cancelled."
    exit 0
  fi
else
  FORK_URL="https://github.com/$GITHUB_USER/$REPO_NAME.git"
  SKIP_FORK=false
fi

# Get optional feature branch (from argument or prompt)
if [[ -z "$2" ]]; then
  read -r "FEATURE_BRANCH?Enter feature branch name (press Enter to skip): "
else
  FEATURE_BRANCH="$2"
fi

LOCAL_PATH="$BASE_DIR/$REPO_NAME"

# Display configuration
printf "\n"
info_printf "Configuration:"
printf "🔗 Original repo: %s\n" "$REPO_URL"
printf "📦 Repo name: %s\n" "$REPO_NAME"
printf "👤 GitHub user: %s\n" "$GITHUB_USER"
printf "📂 Target directory: %s\n" "$LOCAL_PATH"
[[ -n "$FEATURE_BRANCH" ]] && printf "🌿 Feature branch: %s\n" "$FEATURE_BRANCH"

# Check if directory already exists
if [[ -d "$LOCAL_PATH" ]]; then
  printf "\n"
  warning_printf "Directory already exists: $LOCAL_PATH"
  printf "Choose an action:\n"
  printf "  1) Delete and re-clone\n"
  printf "  2) Skip cloning and just setup remotes\n"
  printf "  3) Cancel\n"
  read -r "choice?Enter choice (1-3): "
  
  case "$choice" in
    1)
      clean_printf "Removing existing directory..."
      rm -rf "$LOCAL_PATH"
      ;;
    2)
      SKIP_CLONE=true
      cd "$LOCAL_PATH" || exit 1
      ;;
    *)
      info_printf "Operation cancelled."
      exit 0
      ;;
  esac
fi

# Ensure base directory exists
mkdir -p "$BASE_DIR"

# --- FORK ---
if [[ "$SKIP_FORK" != true ]]; then
  printf "\n"
  format_printf "Forking $REPO_NAME to your account..." "magenta" "bold" "🍴"
  
  # Check if fork already exists
  if gh repo view "$GITHUB_USER/$REPO_NAME" &>/dev/null; then
    success_printf "Fork already exists in your account"
  else
    if ! gh repo fork "$REPO_URL" --clone=false --remote=false; then
      error_printf "Fork failed. Check repository access and permissions." true
    fi
    time_printf "Waiting for fork to be ready..."
    sleep 3
  fi
fi

# --- CLONE ---
if [[ "$SKIP_CLONE" != true ]]; then
  cd "$BASE_DIR" || { error_printf "Cannot access $BASE_DIR" true; }
  
  printf "\n"
  format_printf "Cloning your fork..." "cyan" "bold" "📥"
  if ! git clone "$FORK_URL"; then
    error_printf "Clone failed. Check network connection and repository access." true
  fi
  
  cd "$REPO_NAME" || { error_printf "Cannot access cloned directory" true; }
fi

# --- UPSTREAM ---
if [[ "$SKIP_FORK" != true ]]; then
  printf "\n"
  format_printf "Adding upstream remote..." "blue" "bold" "🔗"
  
  # Remove existing upstream if present
  git remote remove upstream &>/dev/null
  
  if ! git remote add upstream "$REPO_URL"; then
    warning_printf "Failed to add upstream remote (may already exist)"
  fi
fi

printf "\n"
success_printf "Current remotes:"
git remote -v

# --- OPTIONAL FEATURE BRANCH ---
if [[ -n "$FEATURE_BRANCH" ]]; then
  printf "\n"
  format_printf "Creating feature branch: $FEATURE_BRANCH" "green" "bold" "🌿"
  
  # Validate branch name
  if ! git check-ref-format --branch "$FEATURE_BRANCH" &>/dev/null; then
    warning_printf "Invalid branch name format. Using default branch."
  elif git rev-parse --verify "$FEATURE_BRANCH" &>/dev/null; then
    warning_printf "Branch already exists. Switching to it..."
    git checkout "$FEATURE_BRANCH"
  else
    git checkout -b "$FEATURE_BRANCH"
    success_printf "Branch '$FEATURE_BRANCH' created and checked out"
  fi
else
  printf "\n"
  format_printf "No feature branch specified. Staying on default branch." "blue" "💡"
fi

# --- FINAL SUMMARY ---
# Create setup summary file
printf "\n"
format_printf "Creating setup summary file..." "cyan" "bold" "📝"
create_setup_summary

printf "\n"
printf "──────────────────────────────────────────────\n"
rocket_printf "Setup Complete!"
printf "──────────────────────────────────────────────\n"
printf "📂 Local path : %s\n" "$LOCAL_PATH"
printf "🌐 Fork URL   : %s\n" "$FORK_URL"
printf "🔗 Upstream   : %s\n" "$REPO_URL"
[[ -n "$FEATURE_BRANCH" ]] && printf "🌿 Branch     : %s\n" "$FEATURE_BRANCH"
printf "──────────────────────────────────────────────\n"
printf "Next steps:\n"
printf "  cd \"%s\"\n" "$LOCAL_PATH"
printf "  \n"
printf "  # Make your changes, then:\n"
printf "  git add .\n"
printf "  git commit -m \"Your descriptive commit message\"\n"
printf "  git push origin %s\n" "${FEATURE_BRANCH:-main}"
printf "  \n"
printf "  # Create a pull request:\n"
printf "  gh pr create --web\n"
printf "──────────────────────────────────────────────\n"
printf "\n"
